# Generated by Django 5.2 on 2025-05-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productoproveedor_producto_and_more'),
        ('productos', '0002_producto_stock_productoproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='productos.productoproveedor'),
        ),
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
