# Generated by Django 5.2 on 2025-06-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventario_producto_delete_productoproveedor'),
        ('productos', '0003_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleentradasalida',
            options={'verbose_name': 'Detalle Entrada/Salida', 'verbose_name_plural': 'Detalles Entrada/Salida'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='productosvencimiento',
            options={'verbose_name': 'Producto Vencimiento', 'verbose_name_plural': 'Productos Vencimiento'},
        ),
        migrations.RemoveField(
            model_name='detalleentradasalida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productosvencimiento',
            name='id',
        ),
        migrations.AddField(
            model_name='detalleentradasalida',
            name='iddetalleentrada',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='idmovimientoinventario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productosvencimiento',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='productosvencimiento',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productos.producto'),
        ),
        migrations.AlterModelTable(
            name='detalleentradasalida',
            table='detalle_entrada_salida',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
        migrations.AlterModelTable(
            name='movimientoinventario',
            table='movimiento_inventario',
        ),
        migrations.AlterModelTable(
            name='productosvencimiento',
            table='productos_vencimiento',
        ),
    ]
