# Generated by Django 5.2 on 2025-05-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
        ),
    ]
