# Generated by Django 5.2 on 2025-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock_productoproveedor'),
        ('suppliers', '0002_alter_proveedor_options_alter_proveedor_idproveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productoproveedor',
            options={'verbose_name': 'Producto-Proveedor', 'verbose_name_plural': 'Productos-Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='unidadesmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idcategoria',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadesmedida',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together={('producto', 'proveedor')},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='productoproveedor',
            table='producto_proveedor',
        ),
        migrations.AlterModelTable(
            name='unidadesmedida',
            table='unidades_medida',
        ),
    ]
